"""empty message

Revision ID: 33ae46e2ff91
Revises: 
Create Date: 2021-06-22 14:31:38.747758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33ae46e2ff91'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('elections',
    sa.Column('idelection', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('start', sa.DATETIME(), nullable=False),
    sa.Column('end', sa.DATETIME(), nullable=False),
    sa.Column('individual', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('idelection'),
    sa.UniqueConstraint('idelection')
    )
    op.create_table('participants',
    sa.Column('idparticipant', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('individual', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('idparticipant'),
    sa.UniqueConstraint('idparticipant')
    )
    op.create_table('electionparticipants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idelection', sa.Integer(), nullable=False),
    sa.Column('idparticipant', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idelection'], ['elections.idelection'], ),
    sa.ForeignKeyConstraint(['idparticipant'], ['participants.idparticipant'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('votes',
    sa.Column('idvote', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guid', sa.String(length=256), nullable=False),
    sa.Column('pollnumber', sa.Integer(), nullable=False),
    sa.Column('electionofficialjmbg', sa.String(length=14), nullable=False),
    sa.Column('election', sa.Integer(), nullable=True),
    sa.Column('valid', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['election'], ['elections.idelection'], ),
    sa.PrimaryKeyConstraint('idvote'),
    sa.UniqueConstraint('idvote')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votes')
    op.drop_table('electionparticipants')
    op.drop_table('participants')
    op.drop_table('elections')
    # ### end Alembic commands ###
