version: '3'

services:
  user:
    image: user
    environment:
      - REDIS_URL=redis
    networks:
      - redisUser
    ports:
      - 5002:5000
#    deploy:
#      replicas:3
  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
#      - redisDeamon
      - redisUser
  deamon:
    image: deamon
    environment:
      - REDIS_URL=redis
      - DATABASE_URL=applicationDB
    networks:
      - appnetDeamon
      - redisUser
networks:
  appnetDeamon:
  redisDeamon:
#  redisUser: