version: '3'

services:

  authenticationDatabase:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
  applicationDatabase:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3307:3306
  redis:
    image: redis
    ports:
      - 6379:6379