version: '3'

services:
  authenticationDB:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10
    volumes:
      - dbdataauth:/var/lib/mysql
    networks:
      - authnet
  authentication:
    image: authentication
    environment:
      - DATABASE_URL=authenticationDB
    ports:
      - 5001:5000
    networks:
      - authnet

  authenticationMigration:
    image: authenticationmigration
    environment:
      - DATABASE_URL=authenticationDB
    networks:
      - authnet
volumes:
  dbdataauth:
networks:
  authnet:
    driver: overlay
