version: '3'

services:
  applicationDB:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10
    volumes:
      - dbdataapp:/var/lib/mysql
    networks:
      - appnet
  application:
    image: application
    environment:
      - DATABASE_URL=applicationDB
    ports:
      - 5002:5000
    networks:
      - appnet

  applicationMigration:
    image: applicationmigration
    environment:
      - DATABASE_URL=applicationDB
    networks:
      - appnet
  user:
    image: user
    environment:
      - REDIS_URL=redis
    networks:
      - redis
    ports:
      - 5003:5000
    deploy:
      replicas:3
  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - redis
  deamon:
    image: deamon
    environment:
      - REDIS_URL=redis
      - DATABASE_URL=applicationDB
    networks:
      - appnet
      - redis

volumes:
  dbdataapp:
networks:
  appnet:
    driver: overlay
  redis:
    driver: overlay
